### PR TITLE
Italian translation proposal

### PR DESCRIPTION
**Pull request by zabaj1**
Translated files for italian language support.
I made no changes to lexigram-cli in order to add support in italian language.

### CODE REVIEW

**Comment by m0ngr31** [comment]
Sorry this is taking me so long to get to!

You need to create the `speech_assets/SampleUtterances.it.txt` file as well. You can do that by hitting the website in `utterances.it.txt`

**Comment by zabaj1** [comment]
Ok, I'll make it as soon as possibile!

**Comment by zabaj1** [comment]
Ok, now all should be ready for merging to base koko repository, let me know it everything is right.
Have a nice day, sir.

**Comment by succo69** [comment]
i see these changes didn't make it to the repo because flask-ask is failing to install with pip >= 9
is there any way to manually install the updated files without passing through github?
btw, alexa.py needs to be updated too, as it right now supports english and deutsch only
`if LANGUAGE and LANGUAGE != 'None' and LANGUAGE == 'de':
  TEMPLATE_FILE = "templates.de.yaml"
else:
  LANGUAGE = 'en'
  TEMPLATE_FILE = "templates.en.yaml"`

**Comment by m0ngr31** [comment]
Italian support added with different PR. Thanks everyone!

**Pull request closed without merging**
